<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <UserSecretsId>dotnet-SubscriptionProcessor-dbe73b1a-7a41-4c8b-9d4a-2c1bc3b6b6ab</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\aspire\ServiceDefaults\ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\..\shared\EventBusRabbitMQ\EventBusRabbitMQ.csproj" />
    <ProjectReference Include="..\..\..\shared\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>

</Project>
