<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <UserSecretsId>dotnet-OrderProcessor-be9dc507-8a5d-4a87-9067-4ce62d2b6225</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\aspire\ServiceDefaults\ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\..\shared\EventBusRabbitMQ\EventBusRabbitMQ.csproj" />
    <ProjectReference Include="..\..\..\shared\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>
</Project>
