<Project Sdk="Aspire.AppHost.Sdk/13.0.1">

  <PropertyGroup>
	<OutputType>Exe</OutputType>
	<IsPackable>false</IsPackable>
    <UserSecretsId>3dcbe420-7211-4d2c-a659-f7ab350d4dd2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <PackageReference Include="Aspire.Hosting.Keycloak" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" />
    <PackageReference Include="Aspire.Hosting.Redis" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.JavaScript.Extensions" />
    <PackageReference Include="Scalar.Aspire" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\services\basket\Basket.Api\Basket.Api.csproj" />
    <ProjectReference Include="..\..\services\catalog\Catalog.Api\Catalog.Api.csproj" />
    <ProjectReference Include="..\..\services\ordering\Ordering.Api\Ordering.Api.csproj" />
    <ProjectReference Include="..\..\services\ordering\OrderProcessor\OrderProcessor.csproj" />
    <ProjectReference Include="..\..\services\ordering\PaymentProcessor\PaymentProcessor.csproj" />
    <ProjectReference Include="..\..\services\ordering\SubscriptionProcessor\SubscriptionProcessor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="realms\realm-export.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
